# Generated by Django 5.2.7 on 2025-11-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='public_functionaries',
            field=models.ManyToManyField(blank=True, related_name='complaints_public_functionaries', to='complaints.publicfunctionary'),
        ),
    ]
