# Generated by Django 5.2.7 on 2025-11-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_designation_alter_respondent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='affidavit',
            field=models.ImageField(blank=True, help_text='Digital affidavit or uploaded image of Affidavit.', null=True, upload_to='complaints/affidavit/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_public_functionaries',
            field=models.BooleanField(default=False, help_text='User Yes to  Public Functionaries'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='post_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
