# Generated by Django 5.2.7 on 2025-11-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_affidavit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Affidavit', 'affidavit')], max_length=50, null=True),
        ),
    ]
