# Generated by Django 5.2.7 on 2025-11-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_documents_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='complaint_affidavit/'),
        ),
    ]
