# Generated by Django 5.2.7 on 2025-11-19 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_documents_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencedocument',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='complaints.complaint'),
        ),
    ]
