# Generated by Django 5.2.7 on 2025-11-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_alter_evidencedocument_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='verify_mob',
            new_name='is_affidavit',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Review', 'Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
