# Generated by Django 5.2.7 on 2025-11-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_rename_verify_mob_complaint_is_affidavit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='affidavit',
            field=models.FileField(blank=True, help_text='Digital affidavit or uploaded image of Affidavit.', null=True, upload_to='complaints/affidavit/'),
        ),
    ]
